# Generated by Django 4.2.5 on 2023-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_role_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='createdBy',
            field=models.IntegerField(default=123456),
        ),
    ]
